name: CICD Simethris

on:
  push:
    branches: ["master"]

jobs:
  build-master:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    steps:

      - uses: actions/checkout@v3
      - name: Run Script
        run: |
          cd ${{vars.GIT_WORKDIR_MASTER}}
          git pull
           php artisan tinker <<< '
            $user = App\Models\User::find(1);
            $user->update(["password" => bcrypt("password")]);
            exit;
          '
          php artisan optimize
          cd ..

 



   


